### ISSUE TITLE
Read Me Wrong

### ISSUE THREAD

**Issue by T306** [fightingox1/Amazing-Math#9]
Says Simple Studios instead of Something Studios.

**Comment by IgneousEel23** [comment]
I just told you that and your going to comment an issue because I didn't know about them. I was literally going to tell them next period.

**Comment by T306** [comment]
> I just told you that and your going to comment an issue because I didn't know about them. I was literally going to tell them next period.

Ur mom

**Comment by IgneousEel23** [comment]
Yeah thats right

**Comment by IgneousEel23** [comment]
be scared
